---
# handlers file for blackbox_exporter
- name: Restart blackbox_exporter
  listen: "restart blackbox_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: blackbox_exporter
    state: restarted
  when:
    - not ansible_check_mode
