---
lint: |
  yamllint .
  ansible-lint .


dependency:
  name: galaxy
driver:
  name: vagrant

platforms:
  - name: vmagent-debian
    box: generic/debian11
    memory: 512
    cpus: 1
#  - name: vmagent-centos
#    box: generic/centos7
#    memory: 512
#    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
