---
- name: Configure unit
  when: ansible_service_mgr == "systemd"
  block:
  - name: "Systemd | Copy VMalert systemd unit file"
    ansible.builtin.template:
      src: systemd-service.j2
      dest: /etc/systemd/system/vic-vmalert.service
      owner: root
      group: root
      mode: 0644
    register: config_template
    notify: Restart VMalert service
    no_log: True

  - name: "Systemd | daemon-reload VMalert service"
    become: true
    ansible.builtin.systemd:
      daemon_reload: true
    when: config_template is changed

  - name: Ensure VMalert service is enabled on boot
    become: true
    ansible.builtin.systemd:
      name: vic-vmalert
      enabled: true

- name: Configure upstart
  when: ansible_service_mgr == "upstart"
  block:
  - name: "Upstart | Install vic-vmalert service file"
    ansible.builtin.template:
      src: "upstart.j2"
      dest: "/etc/init.d/vic-vmalert"
      mode: "0755"
      owner: root
      group: root
    notify: Restart VMalert service
    register: config_template

  - name: "Upstart | Enable vic-vmalert service"
    ansible.builtin.service:
      name: "vic-vmalert"
      enabled: "yes"

- name: Prepare configuration dir
  ansible.builtin.file:
    state: directory
    path: "{{ vic_vm_alert_config_dir }}"
    mode: 0751
    owner: "{{ vic_vm_alert_system_user }}"
    group: "{{ vic_vm_alert_system_group }}"

- name: Configure alerts config
  ansible.builtin.template:
    src: alert_rules.yml
    dest: "{{ vic_vm_alert_rules_config_path }}"
    mode: 0751
    owner: "{{ vic_vm_alert_system_user }}"
    group: "{{ vic_vm_alert_system_group }}"
    validate: "/usr/local/bin/vmalert-prod -dryRun -rule %s"
    backup: yes
  notify: Restart VMalert service
