---
- name: Create alertmanager service file
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service

#- name: Create alertmanager configuration file
#  ansible.builtin.copy:
#    src: alertmanager.yml
#    dest: "{{ alertmanager_config_dir }}"

- name: Create alertmanager configuration file
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config }}"

- name: Create tmpl file
  ansible.builtin.copy:
    src: telegram_new.tmpl
    dest: "{{ alertmanager_config_dir }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable alertmanager service
  ansible.builtin.service:
    name: alertmanager
    enabled: yes
    state: started