---
- name: Download alertmanager binary to local folder
  become: false
  ansible.builtin.get_url:
    url: "{{ alertmanager_binary_url }}"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"

- name: Extract alertmanager tarball
  ansible.builtin.unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
    mode: '0755'

- name: copy alertmanager
  ansible.builtin.copy:
    src: "{{ alertmanager_install_dir }}alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: /usr/local/bin/
    remote_src: yes
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
    mode: '0755'

- name: copy amtool
  ansible.builtin.copy:
    src: "{{ alertmanager_install_dir }}alertmanager-{{ alertmanager_version }}.linux-amd64/amtool"
    dest: /usr/local/bin/
    remote_src: yes
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
    mode: '0755'

- name: Remove alertmanager tarball
  ansible.builtin.file:
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    state: absent