---
vic_vm_alert_version: "v1.95.0"

vic_vm_alert_repo_url: "https://github.com/VictoriaMetrics/VictoriaMetrics"
vic_vm_alert_platform: "{% if vic_vm_alert_version.replace('v', '') is version('1.79.0', '>=') %}-linux{% endif %}"
vic_vm_alert_download_url: "{{ vic_vm_alert_repo_url }}/releases/download/{{ vic_vm_alert_version }}/vmutils{{ vic_vm_alert_platform }}-{{ go_arch }}-{{ vic_vm_alert_version }}.tar.gz"
vic_vm_alert_system_user: "vic_vm_alert"
vic_vm_alert_system_group: "{{ vic_vm_alert_system_user }}"
vic_vm_alert_config_dir: "/opt/vic-vmalert"
vic_vm_alert_rules_config_path: "/opt/vic-vmalert/rules.yml"
vic_vm_alert_alertmanager_url: "http://localhost:9093"
vic_vm_alert_datasource_url: "http://localhost:8428"
vic_vm_alert_evaluation_interval: "30s"
vic_vm_alert_service_args:
  "httpListenAddr": "0.0.0.0:9431"
  "datasource.url": "{{ vic_vm_alert_datasource_url }}"
  "notifier.url": "{{ vic_vm_alert_alertmanager_url }}"
  "rule": "{{ vic_vm_alert_rules_config_path }}"
  "evaluationInterval": "{{ vic_vm_alert_evaluation_interval }}"

vic_vm_alert_max_open_files: 2097152

# Great examples of alerts - https://awesome-prometheus-alerts.grep.to/rules.html
vic_vm_alert_rules:
  - name: ansible managed alert rules
    rules:
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: '{% raw %}Host out of memory (instance {{ $labels.instance }}){% endraw %}'
          description: '{% raw %}"Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"{% endraw %}'
  - name: general.rules
    rules:
#1 Это предупреждение, предназначенное для обеспечения работоспособности всего конвейера
      - alert: Watchdog
        annotations:
          description: This is an alert meant to ensure that the entire alerting pipeline is functional.
          summary: An alert that should always be firing to certify that Alertmanager is working properly.
        expr: vector(1)
        labels:
          severity: info
#2 Этот алерт должен попадать в ресивер NULL и сконфигурирован и запрещать алерты с уровнем Info
      - alert: InfoInhibitor
        annotations:
          description:  Этот алерт должен попадать в ресивер NULL и сконфигурирован и запрещать алерты с уровнем Info
          summary: Info-level alert inhibition.
        expr: ALERTS{severity = "info"} == 1 unless on(namespace) ALERTS{alertname!= "InfoInhibitor", severity =~ "warning|critical", alertstate="firing"} == 1
        labels:
          severity: info
#3 Этот алерт проверяет доступность Targets и срабатывет при падении любого.
      - alert: TargetDown
        annotations:
          description: '{% raw %}{{ $value }}% of the {{ $labels.job }}/{{$labels.service }} targets in {{ $labels.namespace }} namespace are down.{% endraw %}'
          summary: '{% raw %}Один или несколько targets недоступен.{% endraw %}'
        expr: 100 * (count(up == 0) BY (datacenter,job, namespace, service) / count(up) BY (datacenter,job, namespace, service)) > 10
        for: 10m
        labels:
          severity: warning
#4 Правило по тротлингу по CPU для подов
      - alert: CPUThrottlingHigh
        expr: sum by (container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=""}[5m])) / sum by (container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m])) > (25 / 100)
        for: 15m
        labels:
          severity: info
        annotations:
          description: '{% raw %}throttling of CPU in namespace {{ $labels.namespace }} for container {{ $labels.container }} in pod {{ $labels.pod }}.{% endraw %}'
          summary: '{% raw %}Processes experience elevated CPU throttling.{% endraw %}'
  - name: pve-exporter.rules
    rules:
#1 Проверка на остаток места на файловой системе ноды осталось 5%
      - alert: GuestFilesystemAlmostOutOfSpace
        expr: ((pve_disk_usage_bytes / pve_disk_size_bytes) * 100 > 95)
        for: 30m
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Filesystem on  {{ $labels.id }}  at {{ $labels.instance }} has only {{ printf $value }}% available space left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 5% space left.{% endraw %}'
#2 Проверка на остаток места на файловой системе ноды осталось 3%
      - alert: GuestFilesystemAlmostOutOfSpace
        expr: ((pve_disk_usage_bytes / pve_disk_size_bytes) * 100 > 97)
        for: 30m
        labels:
          severity: critical
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.id }} at {{ $labels.instance }} has only {{ printf $value }}% available space left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 3% space left.{% endraw %}'
 
#3 Заканчивается память на гостевой системе осталось 10%
      - alert: GuestMemoryAlmostOver
        expr: ((pve_memory_usage_bytes / pve_memory_size_bytes) * 100 > 90)
        for: 1h
        labels:
          severity: warning
        annotations:
          description:  '{% raw %}memory {{ $labels.id }} is almost gone {{ printf  $value }}  {{ $labels.instance }}{% endraw %}'
          summary: '{% raw %}The memory is almost gone{% endraw %}'

#4 Заканчивается память на гостевой системе осталось 5% 
      - alert: GuestMemoryAlmostOver
        expr: ((pve_memory_usage_bytes / pve_memory_size_bytes) * 100 > 95)
        for: 1h
        labels:
          severity: warning
        annotations:
          description:  '{% raw %}memory {{ $labels.id }} is almost gone {{ printf  $value }}  {{ $labels.instance }}{% endraw %}'
          summary: '{% raw %}The memory is almost gone{% endraw %}'

#5 Гостевая виртуальная машина перезагружена
      - alert: VirtualMachineRestarted
        expr: pve_uptime_seconds < 300
        labels:
          severity: warning
        annotations:
          description: '{% raw %}The virtual machine {{ $labels.id }} has been restarted {{ $labels.instance }} .{% endraw %}'
          summary: '{% raw %}Virtual machine has restarted.{% endraw %}'

#6 Гостевая виртуальная машина выключена
      - alert: VirtualMachineShutdown
        expr: pve_uptime_seconds == 0
        for: 1h
        labels:
          severity: warning
        annotations:
          description: '{% raw %}The virtual machine {{ $labels.id }} has been shutdown {{ $labels.instance }}.{% endraw %}'
          summary: '{% raw %}Virtual machine has been shutdown.{% endraw %}'
  
#7 На гостевой виртуальной машине загрузка процессора максимальна
      - alert: GuestHighCpuUsage
        expr: (pve_cpu_usage_ratio * 100) > 90
        for: 30m
        labels:
          severity: critical
        annotations:
          description: '{% raw %}High CPU usage on guest virtual machine {{ $labels.instance }}. Current usage {{ printf "%.2f" $value }}%.{% endraw %}'
          summary: '{% raw %}CPU usage on guest virtual machine is above the threshold.{% endraw %}'

  - name: node-exporter.rules
    rules:
  #1 Проверка на остаток места на файловой системе ноды плюс прогнозирование окончания места в 24 часа
      - alert: NodeFilesystemSpaceFillingUp
        expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 15 and predict_linear(node_filesystem_avail_bytes{fstype!="",job="node-exporter"}[6h], 24 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up.{% endraw %}'
          summary: '{% raw %}Filesystem is predicted to run out of space within the next 24 hours.{% endraw %}'
  #2 Проверка на остаток места на файловой системе ноды плюс прогнозирование окончания места в 4 часа
      - alert: NodeFilesystemSpaceFillingUp
        expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 10 and predict_linear(node_filesystem_avail_bytes{fstype!="",job="node-exporter"}[6h], 4 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: critical
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up fast.{% endraw %}'
          summary: '{% raw %}Filesystem is predicted to run out of space within the next 4 hours.{% endraw %}'
  #3 Проверка на остаток места на файловой системе ноды осталось 5%
      - alert: NodeFilesystemAlmostOutOfSpace
        expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 5 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 30m
        labels:
          severity: warning
        annotations:
          description: '{% raw %} Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 5% space left.{% endraw %}'
  #4 Проверка на остаток места на файловой системе ноды осталось 3%
      - alert: NodeFilesystemAlmostOutOfSpace
        expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 3 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 30m
        labels:
          severity: critical
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 3% space left.{% endraw %}'
  #5 Проверка на остаток количество инодов  файловой системе ноды плюс прогнозирование окончания инодов в 24 часа
      - alert: NodeFilesystemFilesFillingUp
        expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 40 and predict_linear(node_filesystem_files_free{fstype!="",job="node-exporter"}[6h], 24 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.{% endraw %}'
          summary: '{% raw %}Filesystem is predicted to run out of inodes within the next 24 hours.{% endraw %}'
  #6 Проверка на остаток количество инодов  файловой системе ноды плюс прогнозирование окончания инодов в 4 часа
      - alert: NodeFilesystemFilesFillingUp
        expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 20 and predict_linear(node_filesystem_files_free{fstype!="",job="node-exporter"}[6h], 4 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: critical
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up fast.{% endraw %}'
          summary: '{% raw %}Filesystem is predicted to run out of inodes within the next 4 hours.{% endraw %}'
  #7 Проверка на остаток количество инодов  файловой системе ноды осталось 5%
      - alert: NodeFilesystemAlmostOutOfFiles
        expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 5 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 5% inodes left.{% endraw %}'
  #8 Проверка на остаток количество инодов  файловой системе ноды осталось 3%
      - alert: NodeFilesystemAlmostOutOfFiles
        expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 3 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
        for: 1h
        labels:
          severity: critical
        annotations:
          description: '{% raw %}Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.{% endraw %}'
          summary: '{% raw %}Filesystem has less than 3% inodes left.{% endraw %}'
  #9 Сетевой интерфейс сообщает о многих ошибках получения.
      - alert: NodeNetworkReceiveErrs
        expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
        for: 1h
        labels:
          severity: warning
        annotations:
          description:  '{% raw %}interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} receive errors in the last two minutes {{ $labels.instance }}{% endraw %}'
          summary: '{% raw %}Network interface is reporting many receive errors.{% endraw %}'
  #10 Сетевой интерфейс сообщает о многих исходящих ошибках . 
      - alert: NodeNetworkTransmitErrs
        expr: rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
        for: 1h
        labels:
          severity: warning
        annotations:
          description: '{% raw %}interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} transmit errors in the last two minutes.{% endraw %}'
          summary: '{% raw %}Network interface is reporting many transmit errors.{% endraw %}'
  #11 Количество коннтреков приближается к пределу (отслеживание количества соединений) 75%
      - alert: NodeHighNumberConntrackEntriesUsed
        expr: (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
        labels:
          severity: warning
        annotations:
          description: '{% raw %}of {{ $labels.exported_instance }} conntrack entries are used {{ printf "%.0f" $value }} .{% endraw %}'
          summary: '{% raw %}Number of conntrack are getting close to the limit.{% endraw %}'
  #12 Node Exporter не смог очистить цель. (ScrapeError)
      - alert: NodeTextFileCollectorScrapeError 
        expr: node_textfile_scrape_error{job="node-exporter"} == 1
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Node Exporter  {{ $labels.exported_instance }} text file collector failed to scrape.{% endraw %}'
          summary: '{% raw %}Node Exporter text file collector failed to scrape.{% endraw %}'
  #13 Неправильное время на ноде
      - alert: NodeClockSkewDetected
        expr: (node_timex_offset_seconds{job="node-exporter"} > 0.05 and deriv(node_timex_offset_seconds{job="node-exporter"}[5m]) >= 0) or (node_timex_offset_seconds{job="node-exporter"} < -0.05 and deriv(node_timex_offset_seconds{job="node-exporter"}[5m]) <= 0)
        for: 10m
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Clock on {{ $labels.exported_instance }} is out of sync by more than 300s. Ensure NTP is configured correctly on this host.{% endraw %}'
          summary: '{% raw %}Clock skew detected.{% endraw %}'
  #14 Часы на ноде не синхранизируются
      - alert: NodeClockNotSynchronising
        expr: min_over_time(node_timex_sync_status{job="node-exporter"}[5m]) == 0 and node_timex_maxerror_seconds{job="node-exporter"} >= 16
        for: 10m
        labels:
          severity: warning
        annotations:
          description: '{% raw %}Clock on {{ $labels.exported_instance }} is not synchronising. Ensure NTP is configured on this host.{% endraw %}'
          summary: '{% raw %}Clock not synchronising.{% endraw %}'
  #15 Деградировал RAID на ноде
      - alert: NodeRAIDDegraded
        expr: node_md_disks_required{device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)",job="node-exporter"} - ignoring (state) (node_md_disks{device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)",job="node-exporter",state="active"}) > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          description: '{% raw %}RAID array {{ $labels.device }} on {{ $labels.exported_instance }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically.{% endraw %}'
          summary: '{% raw %}RAID Array is degraded{% endraw %}'
  
  #16 На ноде заканчиваются доступные дескрипторы файлов занято больше 90%
      - alert: NodeFileDescriptorLimit
        expr: (node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 90)
        for: 15m
        labels:
          severity: critical
        annotations:
          description: '{% raw %}File descriptors limit at {{ $labels.instance }} is currently at {{ printf "%.2f" $value }}%.{% endraw %}'
          summary: '{% raw %}Kernel is predicted to exhaust file descriptors limit soon.{% endraw %}'

