---
# handlers file for pve-exporter
- name: Restart node_exporter
  listen: "restart pve_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: pve_exporter
    state: restarted
  when:
    - not ansible_check_mode
