---
# handlers file for karma
- name: Restart alertmanager
  listen: "restart alertmanager"
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: alertmanager
    state: restarted
  when:
    - not ansible_check_mode
