---
vmagent_version: "v1.95.0"

vmagent_repo_url: "https://github.com/VictoriaMetrics/VictoriaMetrics"
vmagent_platform: "{% if vmagent_version.replace('v', '') is version('1.79.0', '>=') %}-linux{% endif %}"
vmagent_download_url: "{{ vmagent_repo_url }}/releases/download/{{ vmagent_version }}/vmutils{{ vmagent_platform }}-{{ go_arch }}-{{ vmagent_version }}.tar.gz"
vmagent_system_user: "vic_vm_agent"
vmagent_system_group: "{{ vmagent_system_user }}"
vmagent_config_dir: "/opt/vic-vmagent"
vmagent_sd_config_dir: "{{ vmagent_config_dir }}/file_sd_configs"
vmagent_remote_write_host: "http://localhost:8428"
suppressScrapeErrors: "false"
vmagent_service_args:
  "remoteWrite.url": "{{ vmagent_remote_write_host }}/api/v1/write"
  "promscrape.config": "{{ vmagent_config_dir }}/config.yml"
  "remoteWrite.tmpDataPath": /tmp/vmagent
  "remoteWrite.streamAggr.config": "{{ vmagent_config_dir }}/aggregation.yml"
  "promscrape.suppressScrapeErrors": "{{ suppressScrapeErrors }}"


vmagent_aggregation_config: []

vmagent_install_download_to_control: true

vm_proxy_http: ""
vm_proxy_https: ""

vmagent_exec_start_post: ""
vmagent_exec_stop: ""

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome=
# Available options: 'yes', 'read-only', 'tmpfs'
vmagent_systemd_protect_home: "yes"
