---
- name: Create pve_exporter system group
  ansible.builtin.group:
    name: "{{ pve_exporter_system_group }}"
    state: present
    system: true
  when: pve_exporter_system_group != "root"

- name: Create pve_exporter system user
  ansible.builtin.user:
    name: "{{ pve_exporter_system_user }}"
    groups: "{{ pve_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: pve_exporter_system_user != "root"

- name: Ensure existense of PVE-exporter storage directory
  ansible.builtin.file:
    path: "{{ pve_exporter_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ pve_exporter_system_user }}"
    group: "{{ pve_exporter_system_group }}"

- name: Установка пакета prometheus-pve-exporter
  ansible.builtin.pip:
    name: prometheus-pve-exporter
    virtualenv: /usr/share/pve_exporter/venv
    virtualenv_command: source /usr/share/pve_exporter/venv/bin/activate
    state: present