---
scrape_configs:
  - job_name: vmagent
    static_configs:
      - targets:
          - "172.17.2.243:8429"
  - job_name: VM_single
    static_configs:
      - targets:
          - "172.17.2.243:8428"
  - job_name: node-exporter
    static_configs:
      - targets:
          - "172.19.19.41:9100"
          - "172.19.19.42:9100"
          - "172.19.19.43:9100"
          - "172.17.2.243:9100"
  - job_name: vic-vmalert
    static_configs:
      - targets:
          - "172.17.2.243:9431"
  - job_name: "pve"
    static_configs:
      - targets:
          - "172.19.19.41:9221"
          - "172.19.19.42:9221"
          - "172.19.19.43:9221"
    metrics_path: /pve
  - job_name: blackbox_prod
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://registry.neomsa.ru/
        - https://id.neoflex.ru/
        - http://psa.neoflex.ru/
#        - http://argocd.neoflex.ru:8080/healthz/
        - http://argo-prod.neoflex.ru/
        - http://hasura.neoflex.ru/
        - http://hasura-preprod.neoflex.ru/
#        - http://metrics.neoflex.ru/
        - http://prometheus-metrics.neoflex.ru/
#        - http://mobile-neoportal-new.neoflex.ru/ ## RBAC: access denied
#        - http://mobile-neoportal.neoflex.ru/  ## RBAC: access denied
#        - http://files.neoflex.ru/   ### 503 service temporarily unavailable
#        - http://s3-adapter.neoflex.ru/  ### 503 service temporarily unavailable
        - http://invite.neoflex.ru/
        - http://neoforms.neoflex.ru/
  
  - job_name: blackbox_dev
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://dev-mobile-neoportal.do.neoflex.ru
        - https://dashboard-dev-mobile-neoportal.do.neoflex.ru/
        - https://envrouter.do.neoflex.ru
        - http://argo.do.neoflex.ru/
        - http://dev-junior-report.do.neoflex.ru/
#        - http://kafdrop-dev.do.neoflex.ru  ## доступ постоянно мигает
        - https://id-test-s.neoflex.ru/
        - https://id-test.neoflex.ru/
        - https://id.do.neoflex.ru/
        - http://neoforms-dev.do.neoflex.ru/
        - http://neoforms-test.do.neoflex.ru/
        - http://invite-dev.do.neoflex.ru/
        - http://psa-ci.do.neoflex.ru/
        - http://psa-dev1.do.neoflex.ru/
        - http://psa-dev2.do.neoflex.ru/
        - http://psa-qa1.do.neoflex.ru/
        - http://psa-qa2.do.neoflex.ru/
        - https://test-otp.do.neoflex.ru/

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.2.243:9115

  - job_name: ceph-dev
    static_configs:
      - targets:
          - "172.19.19.41:9283"
          - "172.19.19.42:9283"
          - "172.19.19.43:9283"
    metrics_path: /metrics
  
