---
- name: Create pve_exporter system group
  ansible.builtin.group:
    name: "{{ pve_exporter_system_group }}"
    state: present
    system: true
  when: pve_exporter_system_group != "root"

- name: Create pve_exporter system user
  ansible.builtin.user:
    name: "{{ pve_exporter_system_user }}"
    groups: "{{ pve_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: pve_exporter_system_user != "root"

- name: Ensure existense of pve-exporter storage directory
  ansible.builtin.file:
    path: "{{ pve_exporter_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ pve_exporter_system_user }}"
    group: "{{ pve_exporter_system_group }}"

- name: создание venv среды
  ansible.builtin.shell:
    cmd: |
      python3 -m venv /usr/share/pve_exporter/venv
    executable: /bin/bash
  become: true

- name: активация venv среды и install prometheus-pve-exporter
  ansible.builtin.shell:
    cmd: |
      source /usr/share/pve_exporter/venv/bin/activate
      pip install prometheus-pve-exporter
    executable: /bin/bash
  become: true
