---
- name: Setup VM single
  become: true
  hosts: server
  roles:
    - single

- name: Setup VM agent
  become: true
  hosts: server
  roles:
    - vmagent

- name: Setup node-exporter
  become: true
  hosts: node-exporter
  roles:
    - node_exporter

- name: Setup VMalert
  become: true
  hosts: server
  roles:
    - vmalert

- name: Setup Alertmanager
  become: true
  hosts: server
  roles:
    - alertmanager

- name: Setup Grafana
  become: true
  hosts: server
  roles:
    - grafana
