{
 "title": "CoreDNS",
 "tags": [
  "SERVICE",
  "DNS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(kube_pod_info,datacenter)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{datacenter=\"$datacenter\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({datacenter=\"$datacenter\", job=\"kube-dns\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up CoreDNS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{datacenter=\"$datacenter\",job=\"coredns\"})"
    }
   ]
  },
  {
   "title": "coredns_dns_requests_total",
   "type": "timeseries",
   "description": "Общее количество DNS запросов",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "rate(coredns_dns_requests_total{ datacenter=\"$datacenter\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ exported_instance}}, {{type}}"
    }
   ]
  },
  {
   "title": "coredns_dns_responses_total",
   "type": "timeseries",
   "description": "Общее количество DNS  ответов",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(coredns_dns_responses_total{datacenter=\"$datacenter\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ exported_instance}}"
    }
   ]
  },
  {
   "title": "coredns_dns_request_duration_seconds_sum",
   "type": "timeseries",
   "description": "Длительность DNS запросов ",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "rate(coredns_dns_request_duration_seconds_sum {datacenter=\"$datacenter\"}[$__rate_interval])",
     "legendFormat": "{{ exported_instance}}"
    }
   ]
  },
  {
   "title": "coredns_panics_total",
   "type": "stat",
   "description": "Общее количество ошибок DNS запросов",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(coredns_panics_total{datacenter=\"$datacenter\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ exported_instance}}"
    }
   ]
  },
  {
   "title": "coredns_dns_request_size_bytes",
   "type": "timeseries",
   "description": "Размер  DNS запросов, в байтах",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 7 },
   "targets": [
    {
     "expr": "rate(coredns_dns_request_size_bytes_sum{datacenter=\"$datacenter\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "coredns_dns_response_size_bytes_sum",
   "type": "timeseries",
   "description": "Размер DNS ответов, в байтах",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "rate(coredns_dns_response_size_bytes_sum{datacenter=\"$datacenter\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{datacenter=\"$datacenter\", k8s_app=\"kube-dns\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{datacenter=\"$datacenter\", k8s_app=\"kube-dns\"}[5m])",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{datacenter=\"$datacenter\", k8s_app=\"kube-dns\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}